<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TorrentClient.Application\TorrentClient.Application.csproj" />
    <ProjectReference Include="..\TorrentClient.Domain\TorrentClient.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Adapters\Bencode\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
